services:
  # logcache database
  db:
    image: mariadb
    restart: always
    environment:
      - TZ=America/Nuuk
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=thrukdb
      - MYSQL_USER=thrukdbuser
      - MYSQL_PASSWORD=password
    volumes:
      - /var/lib/mysql

  # thruk itself
  thruk:
    image: tmuncks/thruk
    depends_on:
      - db
    restart: always
    environment:
      - TZ=America/Nuuk
      - LOGCACHE=mysql://thrukdbuser:password@db:3306/thrukdb
      - RUNCRON=1
    volumes:
      - /etc/thruk
      - /var/lib/thruk
      - ./thruk:/etc/thruk/thruk_local.d:ro
    ports:
      - 8080:80